export const GET_ASSIGN_EMPLOYEES_LIST_REQUEST = 'GET_ASSIGN_EMPLOYEES_LIST_REQUEST';
export const GET_ASSIGN_EMPLOYEES_LIST_LOADING = 'GET_ASSIGN_EMPLOYEES_LIST_LOADING';
export const GET_ASSIGN_EMPLOYEES_LIST_SUCCESS = 'GET_ASSIGN_EMPLOYEES_LIST_SUCCESS';
export const GET_ASSIGN_EMPLOYEES_LIST_ERROR = 'GET_ASSIGN_EMPLOYEES_LIST_ERROR';
export const GET_ASSIGN_EMPLOYEES_LIST_RESET = 'GET_ASSIGN_EMPLOYEES_LIST_RESET';




export const CREATE_ASSIGN_EMPLOYEE_REQUEST = 'CREATE_ASSIGN_EMPLOYEE_REQUEST';
export const CREATE_ASSIGN_EMPLOYEE_LOADING = 'CREATE_ASSIGN_EMPLOYEE_LOADING';
export const CREATE_ASSIGN_EMPLOYEE_SUCCESS = 'CREATE_ASSIGN_EMPLOYEE_SUCCESS';
export const CREATE_ASSIGN_EMPLOYEE_ERROR = 'CREATE_ASSIGN_EMPLOYEE_ERROR';
export const CREATE_ASSIGN_EMPLOYEE_RESET = 'CREATE_ASSIGN_EMPLOYEE_RESET';

export const DELETE_ASSIGN_EMPLOYEE_REQUEST = 'DELETE_ASSIGN_EMPLOYEE_REQUEST';
export const DELETE_ASSIGN_EMPLOYEE_LOADING = 'DELETE_ASSIGN_EMPLOYEE_LOADING';
export const DELETE_ASSIGN_EMPLOYEE_SUCCESS = 'DELETE_ASSIGN_EMPLOYEE_SUCCESS';
export const DELETE_ASSIGN_EMPLOYEE_ERROR = 'DELETE_ASSIGN_EMPLOYEE_ERROR';
export const DELETE_ASSIGN_EMPLOYEE_RESET = 'DELETE_ASSIGN_EMPLOYEE_RESET';

export const UPDATE_ASSIGN_EMPLOYEE_REQUEST = 'UPDATE_ASSIGN_EMPLOYEE_REQUEST';
export const UPDATE_ASSIGN_EMPLOYEE_LOADING = 'UPDATE_ASSIGN_EMPLOYEE_LOADING';
export const UPDATE_ASSIGN_EMPLOYEE_SUCCESS = 'UPDATE_ASSIGN_EMPLOYEE_SUCCESS';
export const UPDATE_ASSIGN_EMPLOYEE_ERROR = 'UPDATE_ASSIGN_EMPLOYEE_ERROR';
export const UPDATE_ASSIGN_EMPLOYEE_RESET = 'UPDATE_ASSIGN_EMPLOYEE_RESET';


