export const GET_EMPLOYEES_LIST_REQUEST = 'GET_EMPLOYEES_LIST_REQUEST';
export const GET_EMPLOYEES_LIST_LOADING = 'GET_EMPLOYEES_LIST_LOADING';
export const GET_EMPLOYEES_LIST_SUCCESS = 'GET_EMPLOYEES_LIST_SUCCESS';
export const GET_EMPLOYEES_LIST_ERROR = 'GET_EMPLOYEES_LIST_ERROR';
export const GET_EMPLOYEES_LIST_RESET = 'GET_EMPLOYEES_LIST_RESET';

export const GET_EMPLOYEES_LIST_BYROLE_REQUEST = 'GET_EMPLOYEES_LIST_BYROLE_REQUEST';
export const GET_EMPLOYEES_LIST_BYROLE_LOADING = 'GET_EMPLOYEES_LIST_BYROLE_LOADING';
export const GET_EMPLOYEES_LIST_BYROLE_SUCCESS = 'GET_EMPLOYEES_LIST_BYROLE_SUCCESS';
export const GET_EMPLOYEES_LIST_BYROLE_ERROR = 'GET_EMPLOYEES_LIST_BYROLE_ERROR';
export const GET_EMPLOYEES_LIST_BYROLE_RESET = 'GET_EMPLOYEES_LIST_BYROLE_RESET';



export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST';
export const CREATE_EMPLOYEE_LOADING = 'CREATE_EMPLOYEE_LOADING';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_ERROR = 'CREATE_EMPLOYEE_ERROR';
export const CREATE_EMPLOYEE_RESET = 'CREATE_EMPLOYEE_RESET';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_LOADING = 'DELETE_EMPLOYEE_LOADING';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_ERROR = 'DELETE_EMPLOYEE_ERROR';
export const DELETE_EMPLOYEE_RESET = 'DELETE_EMPLOYEE_RESET';

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_LOADING = 'UPDATE_EMPLOYEE_LOADING';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_ERROR = 'UPDATE_EMPLOYEE_ERROR';
export const UPDATE_EMPLOYEE_RESET = 'UPDATE_EMPLOYEE_RESET';


export const GET_EMPLOYEES_LIST_BYOTHERS_REQUEST = 'GET_EMPLOYEES_LIST_BYOTHERS_REQUEST';
export const GET_EMPLOYEES_LIST_BYOTHERS_LOADING = 'GET_EMPLOYEES_LIST_BYOTHERS_LOADING';
export const GET_EMPLOYEES_LIST_BYOTHERS_SUCCESS = 'GET_EMPLOYEES_LIST_BYOTHERS_SUCCESS';
export const GET_EMPLOYEES_LIST_BYOTHERS_ERROR = 'GET_EMPLOYEES_LIST_BYOTHERS_ERROR';
export const GET_EMPLOYEES_LIST_BYOTHERS_RESET = 'GET_EMPLOYEES_LIST_BYOTHERS_RESET';