export const GET_ATTENDANCES_LIST_REQUEST = 'GET_ATTENDANCES_LIST_REQUEST';
export const GET_ATTENDANCES_LIST_LOADING = 'GET_ATTENDANCES_LIST_LOADING';
export const GET_ATTENDANCES_LIST_SUCCESS = 'GET_ATTENDANCES_LIST_SUCCESS';
export const GET_ATTENDANCES_LIST_ERROR = 'GET_ATTENDANCES_LIST_ERROR';
export const GET_ATTENDANCES_LIST_RESET = 'GET_ATTENDANCES_LIST_RESET';

export const FILTER_ATTENDANCE_LIST_REQUEST = 'FILTER_ATTENDANCE_LIST_REQUEST';
export const FILTER_ATTENDANCE_LIST_LOADING = 'FILTER_ATTENDANCE_LIST_LOADING';
export const FILTER_ATTENDANCE_LIST_SUCCESS = 'FILTER_ATTENDANCE_LIST_SUCCESS';
export const FILTER_ATTENDANCE_LIST_ERROR = 'FILTER_ATTENDANCE_LIST_ERROR';
export const FILTER_ATTENDANCE_LIST_RESET = 'FILTER_ATTENDANCE_LIST_RESET';



export const CREATE_ATTENDANCE_REQUEST = 'CREATE_ATTENDANCE_REQUEST';
export const CREATE_ATTENDANCE_LOADING = 'CREATE_ATTENDANCE_LOADING';
export const CREATE_ATTENDANCE_SUCCESS = 'CREATE_ATTENDANCE_SUCCESS';
export const CREATE_ATTENDANCE_ERROR = 'CREATE_ATTENDANCE_ERROR';
export const CREATE_ATTENDANCE_RESET = 'CREATE_ATTENDANCE_RESET';

export const DELETE_ATTENDANCE_REQUEST = 'DELETE_ATTENDANCE_REQUEST';
export const DELETE_ATTENDANCE_LOADING = 'DELETE_ATTENDANCE_LOADING';
export const DELETE_ATTENDANCE_SUCCESS = 'DELETE_ATTENDANCE_SUCCESS';
export const DELETE_ATTENDANCE_ERROR = 'DELETE_ATTENDANCE_ERROR';
export const DELETE_ATTENDANCE_RESET = 'DELETE_ATTENDANCE_RESET';

export const UPDATE_ATTENDANCE_REQUEST = 'UPDATE_ATTENDANCE_REQUEST';
export const UPDATE_ATTENDANCE_LOADING = 'UPDATE_ATTENDANCE_LOADING';
export const UPDATE_ATTENDANCE_SUCCESS = 'UPDATE_ATTENDANCE_SUCCESS';
export const UPDATE_ATTENDANCE_ERROR = 'UPDATE_ATTENDANCE_ERROR';
export const UPDATE_ATTENDANCE_RESET = 'UPDATE_ATTENDANCE_RESET';


