export const GET_REPORTS_LIST_REQUEST = 'GET_REPORTS_LIST_REQUEST';
export const GET_REPORTS_LIST_LOADING = 'GET_REPORTS_LIST_LOADING';
export const GET_REPORTS_LIST_SUCCESS = 'GET_REPORTS_LIST_SUCCESS';
export const GET_REPORTS_LIST_ERROR = 'GET_REPORTS_LIST_ERROR';
export const GET_REPORTS_LIST_RESET = 'GET_REPORTS_LIST_RESET';


export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST';
export const CREATE_REPORT_LOADING = 'CREATE_REPORT_LOADING';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_ERROR = 'CREATE_REPORT_ERROR';
export const CREATE_REPORT_RESET = 'CREATE_REPORT_RESET';

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_LOADING = 'DELETE_REPORT_LOADING';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_ERROR = 'DELETE_REPORT_ERROR';
export const DELETE_REPORT_RESET = 'DELETE_REPORT_RESET';

export const UPDATE_REPORT_REQUEST = 'UPDATE_REPORT_REQUEST';
export const UPDATE_REPORT_LOADING = 'UPDATE_REPORT_LOADING';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_ERROR = 'UPDATE_REPORT_ERROR';
export const UPDATE_REPORT_RESET = 'UPDATE_REPORT_RESET';


