export const GET_SITES_LIST_REQUEST = 'GET_SITES_LIST_REQUEST';
export const GET_SITES_LIST_LOADING = 'GET_SITES_LIST_LOADING';
export const GET_SITES_LIST_SUCCESS = 'GET_SITES_LIST_SUCCESS';
export const GET_SITES_LIST_ERROR = 'GET_SITES_LIST_ERROR';
export const GET_SITES_LIST_RESET = 'GET_SITES_LIST_RESET';


export const CREATE_SITE_REQUEST = 'CREATE_SITE_REQUEST';
export const CREATE_SITE_LOADING = 'CREATE_SITE_LOADING';
export const CREATE_SITE_SUCCESS = 'CREATE_SITE_SUCCESS';
export const CREATE_SITE_ERROR = 'CREATE_SITE_ERROR';
export const CREATE_SITE_RESET = 'CREATE_SITE_RESET';

export const DELETE_SITE_REQUEST = 'DELETE_SITE_REQUEST';
export const DELETE_SITE_LOADING = 'DELETE_SITE_LOADING';
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS';
export const DELETE_SITE_ERROR = 'DELETE_SITE_ERROR';
export const DELETE_SITE_RESET = 'DELETE_SITE_RESET';

export const UPDATE_SITE_REQUEST = 'UPDATE_SITE_REQUEST';
export const UPDATE_SITE_LOADING = 'UPDATE_SITE_LOADING';
export const UPDATE_SITE_SUCCESS = 'UPDATE_SITE_SUCCESS';
export const UPDATE_SITE_ERROR = 'UPDATE_SITE_ERROR';
export const UPDATE_SITE_RESET = 'UPDATE_SITE_RESET';


