export const GET_PROJECTS_LIST_REQUEST = 'GET_PROJECTS_LIST_REQUEST';
export const GET_PROJECTS_LIST_LOADING = 'GET_PROJECTS_LIST_LOADING';
export const GET_PROJECTS_LIST_SUCCESS = 'GET_PROJECTS_LIST_SUCCESS';
export const GET_PROJECTS_LIST_ERROR = 'GET_PROJECTS_LIST_ERROR';
export const GET_PROJECTS_LIST_RESET = 'GET_PROJECTS_LIST_RESET';





export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_LOADING = 'CREATE_PROJECT_LOADING';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';
export const CREATE_PROJECT_RESET = 'CREATE_PROJECT_RESET';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_LOADING = 'DELETE_PROJECT_LOADING';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';
export const DELETE_PROJECT_RESET = 'DELETE_PROJECT_RESET';

export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_LOADING = 'UPDATE_PROJECT_LOADING';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';
export const UPDATE_PROJECT_RESET = 'UPDATE_PROJECT_RESET';


